name: Run Django Tests

# Toda vez que um usuário fizer push, o workflow será executado
on: [push]

jobs:
  run-django-tests:
    name: Run Django Tests
    runs-on: ubuntu-latest  # Vai executar os testes no ambiente Linux, na última versão

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: mypstgresdb
          POSTGRESQL_PASSWORD: root
          POSTGRESQL_DATABASE: bibliogest

    steps:
      # Passo 1: Fazer checkout do código
      - uses: actions/checkout@v3

      # Passo 2: Configurar o ambiente Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      # Passo 3: Instalar dependências do projeto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Configurar a variável de ambiente para o banco de dados
      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://mypstgresdb:root@localhost:5432/bibliogest" >> $GITHUB_ENV

      # Passo 5: Rodar as migrações do Django
      - name: Run migrations
        run: |
          python manage.py migrate

      # Passo 6: Rodar os testes
      - name: Run tests
        run: |
          python manage.py test
